export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/app',
  SALES: '/sales',
  NEW_SALE: '/sales/new',
  SALE_DETAIL: '/sales/:id',
  SECONDHAND: '/secondhand',
  SECONDHAND_INTAKE: '/secondhand/intake',
  SECONDHAND_RESALE: '/secondhand/resale/:id',
  REPAIRS: '/repairs',
  REPAIR_INTAKE: '/repairs/new',
  REPAIR_DETAIL: '/repairs/:id',
  INVENTORY: '/inventory',
  SPARE_PARTS: '/inventory/parts',
  ALERTS: '/inventory/alerts',
  INVOICES: '/invoices',
  INVOICE_VIEW: '/invoices/:id',
  ANALYTICS: '/analytics',
};
